### ISSUE TITLE
How to get the ssh terminal to Automate on Mac OSX Yosemite?

### ISSUE THREAD

**Issue by blacksun1** [neillturner/ec2dream#4]
Hi Neil,

This is probably not for you as I'm pretty sure you're not running on a Mac but hopefully someone has had the same issue and found a solution.

I've tried a few things and searched high and low on Google for any simple information that would enable something like calling the terminal and opening an ssh connection but I've been unable to find anything.

I tried putting in `/Applications/Utilities/Terminal.app/Contents/MacOS/Terminal` as my xterm but that didn't work. The default XTerm doesn't work either. It just opens up a blank window Xterm with a title of ssh.

Anyone else got any ideas?

Thanks in advance,

**Comment by neillturner** [comment]
i have tested on mac and linux but primarily use windows (no laughing in the back stalls -)). 
have a look in the code:
  https://github.com/neillturner/ec2dream/blob/master/lib/common/ssh.rb
your can set a command in the environment tab in the field TERMINAL EMULATOR on non-windows platforms otherwise it sets the commandf to xterm. 
 when you try to do ssh to box from the server tab you should see the command used in the background command windows.

**Comment by blacksun1** [comment]
The only problem is that the XTerm is really un-user friendly and it would be better if we could open ssh in the standard mac terminal but this - as I've tried it - does not seem to be a trivial thing to do.

**Comment by neillturner** [comment]
I'm sorry i didn't spent alot time on this. Actually the port on my daughters Mac took about a day. If you write a trival ruby program that calls ssh and get it working then we could incorporate it into the code. Currently i'm pretty busy on my open source test-kitchen plugins for puppet and ansible as they are proving to be popular and my puppet forge modules.

**Comment by neillturner** [comment]
old
